# Generated by Django 3.2 on 2021-04-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_contact1_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact1',
            name='customer',
        ),
    ]
